/**
 * Stands in for the `virtual:executor-schemas` module under test.
 *
 * The schemas are generated by a dev-server plugin that the test config deliberately leaves out
 * (see vitest.config.ts). Without a stand-in, importing any component that transitively reaches
 * the settings form fails to resolve — so a test of an unrelated pure helper in the same module
 * could not run at all. No test asserts on schema contents; they only need the import to resolve.
 */
export default {} as Record<string, unknown>;
