import type { IntegrationIssue } from './linear';

export type {
  IntegrationIssue,
  TaskFromIssueDraft,
  TaskSourceDraft,
  LinearPriority,
} from './linear';
export { issueToTaskDraft } from './linear';

const ISSUES: IntegrationIssue[] = [
  {
    id: 'eng-214',
    identifier: 'ENG-214',
    title: 'Fix login redirect after SSO',
    description:
      'After SSO, users land on / instead of the return URL they were sent to sign in from. Preserve `redirect` through the OAuth callback and send them back.',
    status: 'In Progress',
    statusType: 'started',
    statusColor: '#f2c94c',
    team: 'Engineering',
    assignee: 'You',
    labels: ['auth', 'bug'],
    priority: 'High',
    project: 'Kablan',
    cycle: 'Cycle 12',
    estimate: 3,
    dueDate: '2026-09-09',
    url: 'https://linear.app/kablan/issue/ENG-214',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-07T06:12:00.000Z',
  comments: [],
  },
  {
    id: 'eng-198',
    identifier: 'ENG-198',
    title: 'Empty state for archived tasks',
    description:
      'The archive view still uses the active-list empty copy. Write a sentence that says these tasks left the board, and how to restore one.',
    status: 'Todo',
    statusType: 'unstarted',
    statusColor: '#e2e2e2',
    team: 'Engineering',
    assignee: 'You',
    labels: ['frontend'],
    priority: 'Medium',
    project: 'Kablan',
    cycle: 'Cycle 12',
    estimate: 2,
    dueDate: null,
    url: 'https://linear.app/kablan/issue/ENG-198',
    createdAt: '2026-08-28T14:20:00.000Z',
    updatedAt: '2026-09-06T18:40:00.000Z',
  comments: [],
  },
  {
    id: 'eng-176',
    identifier: 'ENG-176',
    title: 'Rate-limit Linear webhooks',
    description:
      'Burst delivery from Linear can stampede the inbox refresh. Debounce inbound webhooks per workspace and coalesce into one fetch.',
    status: 'Todo',
    statusType: 'unstarted',
    statusColor: '#e2e2e2',
    team: 'Platform',
    assignee: 'You',
    labels: ['backend'],
    priority: 'Urgent',
    project: 'Integrations',
    cycle: 'Cycle 12',
    estimate: 5,
    dueDate: '2026-09-08',
    url: 'https://linear.app/kablan/issue/ENG-176',
    createdAt: '2026-08-20T09:15:00.000Z',
    updatedAt: '2026-09-05T11:05:00.000Z',
  comments: [],
  },
  {
    id: 'eng-205',
    identifier: 'ENG-205',
    title: 'Persist draft composer on refresh',
    description:
      'Leaving the new-task dialog and coming back should restore title and description. Store the draft until it is submitted or discarded.',
    status: 'In Progress',
    statusType: 'started',
    statusColor: '#f2c94c',
    team: 'Engineering',
    assignee: 'Jordan Hale',
    labels: ['frontend'],
    priority: 'Low',
    project: 'Kablan',
    cycle: 'Cycle 12',
    estimate: 2,
    dueDate: null,
    url: 'https://linear.app/kablan/issue/ENG-205',
    createdAt: '2026-09-04T16:00:00.000Z',
    updatedAt: '2026-09-07T08:20:00.000Z',
  comments: [],
  },
  {
    id: 'des-41',
    identifier: 'DES-41',
    title: 'Empty-state illustration for All Tasks',
    description:
      'The all-tasks list still uses a text-only empty state. Add the illustration from the board so the two views feel like the same product.',
    status: 'In Review',
    statusType: 'started',
    statusColor: '#4cb782',
    team: 'Design',
    assignee: 'Maya Chen',
    labels: ['design'],
    priority: 'Medium',
    project: 'Kablan',
    cycle: 'Cycle 11',
    estimate: 1,
    dueDate: null,
    url: 'https://linear.app/kablan/issue/DES-41',
    createdAt: '2026-08-22T11:30:00.000Z',
    updatedAt: '2026-09-06T14:00:00.000Z',
  comments: [],
  },
  {
    id: 'plat-12',
    identifier: 'PLAT-12',
    title: 'Document Linear webhook retry policy',
    description:
      'Ops asked how long we retry inbound Linear webhooks and when we give up. Write it down next to the debounce work.',
    status: 'Backlog',
    statusType: 'backlog',
    statusColor: '#95a2b3',
    team: 'Platform',
    assignee: null,
    labels: ['docs'],
    priority: 'No priority',
    project: 'Integrations',
    cycle: null,
    estimate: null,
    dueDate: null,
    url: 'https://linear.app/kablan/issue/PLAT-12',
    createdAt: '2026-08-15T08:00:00.000Z',
    updatedAt: '2026-09-04T09:30:00.000Z',
  comments: [],
  },
  {
    id: 'des-38',
    identifier: 'DES-38',
    title: 'Sidebar icon for Integrations',
    description:
      'Pick a glyph that reads as a connection, not another project. Should sit next to Projects and Agents without looking like a third list of the same thing.',
    status: 'Todo',
    statusType: 'unstarted',
    statusColor: '#e2e2e2',
    team: 'Design',
    assignee: null,
    labels: ['design', 'sidebar'],
    priority: 'Low',
    project: 'Kablan',
    cycle: null,
    estimate: 1,
    dueDate: null,
    url: 'https://linear.app/kablan/issue/DES-38',
    createdAt: '2026-08-18T13:40:00.000Z',
    updatedAt: '2026-09-03T16:45:00.000Z',
  comments: [],
  },
  {
    id: 'eng-190',
    identifier: 'ENG-190',
    title: 'Cancel in-flight Linear fetches on disconnect',
    description:
      'Removing Linear while a refresh is in flight still paints the inbox. Abort the request and clear the list.',
    status: 'In Review',
    statusType: 'started',
    statusColor: '#4cb782',
    team: 'Engineering',
    assignee: 'Maya Chen',
    labels: ['backend'],
    priority: 'High',
    project: 'Integrations',
    cycle: 'Cycle 12',
    estimate: 2,
    dueDate: '2026-09-10',
    url: 'https://linear.app/kablan/issue/ENG-190',
    createdAt: '2026-08-30T17:05:00.000Z',
    updatedAt: '2026-09-05T19:10:00.000Z',
  comments: [],
  },
];

export function linearIssues(): IntegrationIssue[] {
  return ISSUES;
}

export function assignedLinearIssues(): IntegrationIssue[] {
  return ISSUES.filter((issue) => issue.assignee === 'You');
}

export function findLinearIssue(id: string): IntegrationIssue | undefined {
  return ISSUES.find((issue) => issue.id === id);
}
